// Vue/src/orig_App.vue
<template>
  <div>
    <DxDataGrid
      :element-attr="dataGridAttributes"
      :data-source="dataSource"
      key-expr="ID"
      :columns="columns"
      :show-borders="true"
      @toolbar-preparing="onToolbarPreparing"
    >
      <DxColumn
        v-for="column in columns"
        :key="column.dataField"
        :data-field="column.dataField"
        :visible="column.visible"
      />
    </DxDataGrid>

    <CustomColumnChooser
      container="#grid"
      button="#myColumnChooser"
      :visible="visible"
      @hiding="onHiding"
      :columns="columns"
      @apply="onApply"
    />
  </div>
</template>

<script>
import DxDataGrid, { DxColumn } from "devextreme-vue/data-grid";
import CustomColumnChooser from "./components/CustomColumnChooser.vue";
import { customers } from "./data.js";

export default {
  name: 'App',
  components: {
    DxDataGrid,
    DxColumn,
    CustomColumnChooser,
  },

  data() {
    return {
      dataSource: customers,
      columns: [
        {
          dataField: "CompanyName",
          visible: true,
        },
        {
          dataField: "City",
          visible: true,
        },
        {
          dataField: "State",
          visible: false,
        },
        {
          dataField: "Phone",
          visible: true,
        },
        {
          dataField: "Fax",
          visible: true,
        },
      ],
      visible: false,
      dataGridAttributes: {
          id: 'grid'
      }
    };
  },

  methods: {
    onToolbarPreparing(e) {
      e.toolbarOptions.items.push({
        widget: "dxButton",
        location: "after",
        options: {
          icon: "columnchooser",
          elementAttr: {
            id: "myColumnChooser",
          },
          onClick: () => {
            this.visible = true;
          },
        },
      });
    },
    onHiding() {
      this.visible = false;
    },
    onApply(changes) {
      changes.forEach((change) => {
        var column = this.columns.find(
          (column) => column.dataField === change.dataField
        );
        column.visible = change.visible;
      });
      this.visible = false;
    },
  }
}
</script>

<style>
</style>

// React/src/orig_App.js
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.light.css';

import React, { useCallback, useState, useReducer } from "react";

import DataGrid, { Column } from "devextreme-react/data-grid";
import { customers } from "./data.js";
import CustomColumnChooser from "./CustomColumnChooser";

const initialState = [
  {
    dataField: "CompanyName",
    visible: true
  },
  {
    dataField: "City",
    visible: true
  },
  {
    dataField: "State",
    visible: true
  },
  {
    dataField: "Phone",
    visible: true
  },
  {
    dataField: "Fax",
    visible: true
  }
];

function reducer(state, changes) {
  if (Object.keys(changes).length === 0) return state;

  var newState = [...state];
  changes.forEach((change) => {
    var column = newState.find((c) => c.dataField === change.dataField);
    Object.keys(change).forEach((key) => {
      column[key] = change[key];
    });
  });
  return newState;
}

export default function App() {
  const [columns, setColumnsState] = useReducer(reducer, initialState);

  const [visible, setVisible] = useState(false);

  const onToolbarPreparing = useCallback((e) => {
    e.toolbarOptions.items.push({
      widget: "dxButton",
      location: "after",
      options: {
        icon: "columnchooser",
        elementAttr: {
          id: "myColumnChooser"
        },
        onClick: () => setVisible(true)
      }
    });
  }, [setVisible]);

  const onHiding = useCallback(() => {
    setVisible(false);
  }, [setVisible]);

  const onApply = useCallback((changes) => {
    setColumnsState(changes);
    setVisible(false);
  }, [setColumnsState, setVisible]);

  return (
    <React.Fragment>
      <DataGrid
        id="grid"
        dataSource={customers}
        showBorders={true}
        onToolbarPreparing={onToolbarPreparing}
      >
        {columns.map((column) => {
          return (
            <Column
              key={column.dataField}
              dataField={column.dataField}
              visible={column.visible}
            />
          );
        })}
      </DataGrid>

      <CustomColumnChooser
        container="#grid"
        button="#myColumnChooser"
        visible={visible}
        onHiding={onHiding}
        columns={columns}
        onApply={onApply}
      />
    </React.Fragment>
  );
}
